#%RAML 1.0
title: TOTP API
version: v1
baseUri: https://api.samplehost.com
protocols: [HTTPS]
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number

/api-key:
  description: |
    Create a new API Key for this API. This endpoint will send an email with a
    new, unique API Key. You must then make a separate call to activate that API
    Key. Protect your API Key as a secret.
  post:
    body:
      application/json:
        properties:
          email:
            type: string
            required: true
        example: |
          {
            "email": "john_smith@example.com"
          }
    responses:
      204:
      401:

/api-key/activate:
  description: |
    Activate a recently-created API Key. Returns the API Secret needed for
    further calls. This call can only be made once per API Key, so make sure you
    save the API Secret somewhere safe.
  post:
    body:
      application/json:
        properties:
          email:
            type: string
            required: true
          api_key:
            type: string
            required: true
        example: |
          {
            "email": "john_smith@example.com",
            "api_key": "0123456789abcdef0123456789abcdef01234567"
          }
    responses:
      200:
        body:
          application/json:
            properties:
              api_secret:
                type: string
            example: |
              {
                "api_secret": "ABCDEFGHIJKLMNOPQRSTUVWXYZ+abcdefgh/ijklmno="
              }
      401:
      404:

/totp:
  description: |
    Create a new TOTP account. This will return a UUID for that account, along
    with a TOTP key and barcode for the end-user to type in or scan in order to
    add an account to their TOTP-compatible smartphone app.
  post:
    headers:
      X-TOTP-ApiKey:
        description: API Key
        required: true
      X-TOTP-ApiSecret:
        description: API Secret
        required: true
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": "28123f10-e33d-5533-b53f-111ef8d7b14f",
                "key": "ABCDEFGHIJKLMNOPQRSTUVWXYZ+abcdefgh/ijklmno=",
                "image_url": "data:image/gif;base64,..."
              }
      401:

/totp/{id}:
  uriParameters:
    id:
      description: TOTP ID
      type: string
      required: true
  delete:
    headers:
      X-TOTP-ApiKey:
        description: API Key
        required: true
      X-TOTP-ApiSecret:
        description: API Secret
        required: true
    responses:
      204:
      401:
      404:

/totp/{id}/validate:
  uriParameters:
    id:
      description: TOTP ID
      type: string
      required: true
  post:
    headers:
      X-TOTP-ApiKey:
        description: API Key
        required: true
      X-TOTP-ApiSecret:
        description: API Secret
        required: true
    body:
      application/json:
        properties:
          code:
            type: string
        example: |
          {"code": "012345"}
    responses:
      204:
      401:
      404:
