services:
  do-full-recovery:
    build: recovery
    volumes:
      - ./:/data
    working_dir: /data
    command: ./recovery/do-full-recovery.sh

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  dev:
    build: development
    env_file:
      - ./local.env
    volumes:
      - ./:/data
    working_dir: /data

