service: mfa-api

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 30

  # Experimented with various memory sizes. Manually calling the totpValidate
  # function once every few seconds, the average durations were as follows:
  #   512 MB = 48 ms
  #   256 MB = 71 ms
  #   128 MB = 159 ms
  memorySize: 512
  apiKeys:
    - ${self:custom.namespace}_global
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.namespace}_*"

custom:
  stage: ${opt:stage, self:provider.stage}
  namespace: ${self:service}_${self:custom.stage}
  apiKeyTable: ${self:custom.namespace}_api-key
  totpTable: ${self:custom.namespace}_totp
  u2fTable: ${self:custom.namespace}_u2f

package:
  exclude:
    - node_modules/aws-sdk/**

functions:
  apiKeyActivate:
    handler: handlers/api-key.activate
    name: ${self:custom.namespace}_apiKeyActivate
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
    events:
      - http:
          path: api-key/activate
          method: post
          private: true
  apiKeyCreate:
    handler: handlers/api-key.create
    name: ${self:custom.namespace}_apiKeyCreate
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
    events:
      - http:
          path: api-key
          method: post
          private: true
  totpCreate:
    handler: handlers/totp.create
    name: ${self:custom.namespace}_totpCreate
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
      TOTP_TABLE_NAME: ${self:custom.totpTable}
    events:
      - http:
          path: totp
          method: post
  totpDelete:
    handler: handlers/totp.delete
    name: ${self:custom.namespace}_totpDelete
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
      TOTP_TABLE_NAME: ${self:custom.totpTable}
    events:
      - http:
          path: totp/{uuid}
          method: delete
  totpValidate:
    handler: handlers/totp.validate
    name: ${self:custom.namespace}_totpValidate
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
      TOTP_TABLE_NAME: ${self:custom.totpTable}
    events:
      - http:
          path: totp/{uuid}/validate
          method: post
  u2fCreateAuthentication:
    handler: handlers/u2f.createAuthentication
    name: ${self:custom.namespace}_u2fCreateAuthentication
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
      U2F_TABLE_NAME: ${self:custom.u2fTable}
    events:
      - http:
          path: u2f/{uuid}/auth
          method: post
  u2fCreateRegistration:
    handler: handlers/u2f.createRegistration
    name: ${self:custom.namespace}_u2fCreateRegistration
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
      U2F_TABLE_NAME: ${self:custom.u2fTable}
    events:
      - http:
          path: u2f
          method: post
  u2fDelete:
    handler: handlers/u2f.delete
    name: ${self:custom.namespace}_u2fDelete
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
      U2F_TABLE_NAME: ${self:custom.u2fTable}
    events:
      - http:
          path: u2f/{uuid}
          method: delete
  u2fValidateAuthentication:
    handler: handlers/u2f.validateAuthentication
    name: ${self:custom.namespace}_u2fValidateAuthentication
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
      U2F_TABLE_NAME: ${self:custom.u2fTable}
    events:
      - http:
          path: u2f/{uuid}/auth
          method: put
  u2fValidateRegistration:
    handler: handlers/u2f.validateRegistration
    name: ${self:custom.namespace}_u2fValidateRegistration
    environment:
      API_KEY_TABLE_NAME: ${self:custom.apiKeyTable}
      U2F_TABLE_NAME: ${self:custom.u2fTable}
    events:
      - http:
          path: u2f/{uuid}
          method: put

resources:
  Resources:
    ApiKeyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: value
            AttributeType: S
        KeySchema:
          - AttributeName: value
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.apiKeyTable}
    TotpDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.totpTable}
    U2fDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.u2fTable}
    ApiKeyActivateLogGroup:
      Properties:
        RetentionInDays: "30"
    ApiKeyCreateLogGroup:
      Properties:
        RetentionInDays: "30"
    TotpCreateLogGroup:
      Properties:
        RetentionInDays: "30"
    TotpDeleteLogGroup:
      Properties:
        RetentionInDays: "30"
    TotpValidateLogGroup:
      Properties:
        RetentionInDays: "30"
    U2fCreateAuthenticationLogGroup:
      Properties:
        RetentionInDays: "30"
    U2fCreateRegistrationLogGroup:
      Properties:
        RetentionInDays: "30"
    U2fDeleteLogGroup:
      Properties:
        RetentionInDays: "30"
    U2fValidateAuthenticationLogGroup:
      Properties:
        RetentionInDays: "30"
    U2fValidateRegistrationLogGroup:
      Properties:
        RetentionInDays: "30"
